### ISSUE TITLE
2 - Infer ploidy of X and Y - create framework to compare input sample data to reference set

### ISSUE THREAD

**Issue by mathbionerd** [WilsonSayresLab/XYalign#10]
Need to compare (a) depth and (b) read balance between input sample and reference to infer ploidy (and constitution) of sex chromosomes in the sample. 
- can compare means with statistical test
- can generate a likelihood model 

(a) read depth
- divide sample in windows on X, Y, and reference autosome
- calculate mean depth in each window
- generate a distribution by pulling 1000 random X mean depth windows, 1000 random Y mean depth windows, and 1000 random autosomal mean depth windows, and calculating the ratio of mean depth in each window (X/A, Y/A).
- KS-test between input distribution and each reference distribution to find the best fit match against
- alternatively - consider likelihood framework.

(b) read balance
- for all variant sites, calculate read balance for X, Y, and reference autosome
- plot plot read balance of sample in black and read balance of the best fit distribution in grey as output for the user.
- KS-test between input distribution and each reference distribution of read balance to find the best fit match against (do we need to test it this way - can we test for deviation from the mean?)
- alternatively - consider likelihood framework.

(c) combine evidence from (a) and (b) to make ploidy call.

**Comment by thw17** [comment]
Right now, we're going with a simple threshold based on the bootstrap because it's the most useful.  This problem will be of central interest moving forward, but for now we have something that works, so I'm closing this issue
