### ISSUE TITLE
Reference depth/quality filter

### ISSUE THREAD

**Issue by mathbionerd** [WilsonSayresLab/XYalign#12]
In addition to the reference genome mask, we will have a default reference quality & depth mask based on the combination of all the high coverage 1000 genomes samples. 

Need to run depth/quality assessment to generate a default mask for depth/quality across all high coverage 1000 genomes individuals for each reference genome build: a) hg19, b) hg38, c)GRCh38.

**Comment by mathbionerd** [comment]
Just food for thought. Here is the summary of the rationale used for filtering the Y chromosome in Poznik et al (2013): 

[http://science.sciencemag.org/content/sci/suppl/2013/08/01/341.6145.562.DC1/Poznik.SM.pdf](http://science.sciencemag.org/content/sci/suppl/2013/08/01/341.6145.562.DC1/Poznik.SM.pdf)

> **Callability Mask**: To learn directly from the read data the boundaries of the regions within which short-read sequencing could yield reliable variant calls, we calculated average filtered read depth across all samples in contiguous 1 kb windows and computed an exponentially-weighted moving average (EWMA) ￼ Fig. 1 of these values (deviated from a narrow envelope were identified as problematic. Those of depressed depth corresponded to ampliconic sequences, within which reads do not map uniquely and were thus filtered out. Regions of inflated depth corresponded to heterochromatin, where naïve application of standard genotype calling methods would give the impression of abundant heterozygosity due to the pileup of highly similar reads around the borders of unassembled regions. After constructing the depth-based filter, we repeated this procedure for the MQ0 ratio, the proportion of unfiltered reads with fully ambiguous mapping. Although the X-transposed region showed no deviation in the depth-based mask, it failed the MQ0 ratio based mask. In females we found depressed read depth in the homologous region of the X chromosome (Fig. S2); we hypothesize that in males, each of whom possesses one X and one Y, there is an equal exchange of mismapped reads between the two chromosomes. The depth and MQ0 masks were merged and smoothed, leaving 10.45 Mb of sequence for down-stream quality control.
> 
> **Site-Level Quality Control**: With the regional mask in hand, we defined a series of site-level quality control filters (Fig. S3A). Of the 22,974,737 mapped coordinates, 12,532,580 fell within the bounds of the regional exclusion mask. A further 129,411 were excluded due to an MQ0 ratio greater than or equal to 0.10, and 170,144 were excluded because more than 20 samples had missing genotypes, either due to an absence of sequencing reads or to a heterozygous maximum likelihood genotype (Fig. S3B). The remaining polymorphic sites had a median depth (across all samples) of 265, and we filtered out all sites whose depth was outside three median absolute deviations of this value, thus excluding 12,425 with depth above 371 and 141,512 below 159 (Fig. S3C). Finally, we culled 547 sites with a heterozygous maximum likelihood genotype in more than seven samples (Fig. S3D). This left 9,988,118 callable sites. Of 432 ISOGG SNPs with observed variation in our data, 4393 pass the regional and mapping quality filters, and of these, just one failed the missingness filter and a further two the depth filter.

**Comment by thw17** [comment]
Closing this for now, as it doesn't really fit the current goals of XYalign (i.e., the goals of XYalign are not to do the variant calling for users - the before/after with Platypus is more for diagnostic purposes).  Perhaps we can discuss including packaged masks for users to choose from down the line.
