### ISSUE TITLE
PREPARE_REFERENCE

### ISSUE THREAD

**Issue by pickpingk** [WilsonSayresLab/XYalign#23]
hello！
When I want to use xyalign, I need to make mask.bed. I choose to use the files in Files/masks/ucsc_hg38/ to combine them for mask.bed file generation. Am I doing this right?

**Comment by thw17** [comment]
Assuming you're working with human data and mapping to hg38 and looking for a default mask, I'd probably aim to just use the PAR mask, which is "hg38_PAR_Ymask_startEnd.bed" in Files/masks/PARs/. Though see the readme in that directory if you're using a different genome.

**Comment by pickpingk** [comment]
Ok, I will use the file you mentioned to build mask.bed. Thank you for your reply and have a nice day
