### ISSUE TITLE
Develop re-aligning pipeline for X/Y complement

### ISSUE THREAD

**Issue by mathbionerd** [WilsonSayresLab/XYalign#4]
Develop and implement re-aligning pipeline based on inferred sex chromosome ploidy. This issue is to deal with whether we think the sample has a Y chromosome in it or not: 
- If there is no Y chromosome, strip reads from X and Y, and re-align all just to the X chromosome
- If there is a Y chromosome, strip reads from X and Y, and re-align (with more stringent parameters??) to X and to Y chromosome with PAR1 and PAR2 masked out
- Need to have the correct reference - start with GRCh38/hg38
- Will extend to include hg19/GRCh37
- Create new BAM file with updated X and Y alignments for input into your favorite variant caller

**Comment by mathbionerd** [comment]
MWS to provide a masked chrY fasta for re-aligning reads when a Y chromosome is inferred (GRCh38).

**Comment by thw17** [comment]
Do we want a masked Y for mapping (reads will be generated from those regions and mismap to new regions when they're not available) or just for variant calling?

**Comment by thw17** [comment]
Just added functions to XYalign.py to isolate sex chromosomes from the reference genome, strip reads, remap based on presence/absence of Y chromosome, remove sex chromosomes from original bam, merge remapped reads with sex chromosome-less bam, and reheader using the original bam header.

**Comment by mathbionerd** [comment]
There are two Y chromosome masks: 
1. Mapping mask: 
   The Y chromosome masked for re-mapping reads - masked for regions that are identical between X and Y, so that we don't decrease our power to call variants in these regions (PAR1, and PAR2 for sure ... haven't looked at XTR). 
2. XYalign variant/depth/quality mask:
   This will mask out regions that we don't want to use for our inference of X-Y copy number because we don't trust depth or quality in these regions - we also probably don't trust variant calling in these regions.

**Comment by Madelinehazel** [comment]
Ah, just saw this Tim, thanks for doing that. I have a shell script for the realignment of X and Y reads but looks like that won't be needed!

**Comment by mathbionerd** [comment]
@thw17 and @Madelinehazel - how is this going? 

Also, I have some of the 1000genomes high coverage now uploaded to the CGC, which everyone should have access to, so we can start the stripping and realigning to: 

hg19
hg38
GRCh38

Does someone have the ftp links to the reference genomes here - you should be able to upload them yourself to the CGC, or I can do it if you share the link. 

I'm thinking it might be pretty time intensive to do this for all the samples, so maybe we should choose just a couple samples? Or, at a minimum, see how long and how much it costs, to do this for a representative 46,XX and 46,XY individual.

**Comment by thw17** [comment]
If we are able to run things in parallel, it won't

**Comment by thw17** [comment]
Sorry, accidentally hit save above.

If we run things in parallel, it won't necessarily take any longer to run more samples. Not sure how much bandwidth we have on 7 bridges though

**Comment by Phillip-a-richmond** [comment]
Don't you get billed for CPU-hours?  If you need somewhere to run some mapping comparisons I can do that on my local machine and then move the XY sub-selected BAMs to 7 bridges.

**Comment by mathbionerd** [comment]
It runs tremendously fast. Unfortunately I cannot apply the AWS credit, but I'm willing to pay some to get this project finished quickly. I don't know how the download is going to our local server, but I now have all the .bai files, and four full .bam files on CGC. 

One of the major problems is just getting the complete BAM files anywhere. If someone wants to run realignment in parallel (for the different reference builds), that'd be great. @Madelinehazel? @Phillip-a-richmond? Do you think you can get these files quickly?

In any case, we've already had a good experience getting things to run quickly on CGC, and I'm okay allocating some startup to pay for using it to finish this project on time.

**Comment by thw17** [comment]
@mwilsonsayres the download isn't going well on our cluster, so it looks like CGC might be the way to go, unless we go the SRA route to download the raw reads and assemble ourselves.

**Comment by ekarlins** [comment]
Have you tried downloading using Aspera?

**Comment by mathbionerd** [comment]
I guess it depends on what you want to do with these files - if we want to have genomes aligned to hg19 and hg38, then SRA may be the way to go (which I think it is). 

To avoid the extra steps of stripping and reordering. In any case, we can start with just a single XX and XY individual - if we can all agree on which two to look at.

**Comment by mathbionerd** [comment]
Has anyone made the reference Y chromosomes for re-aligning?

I'm debating about whether we should have this as a reference file, or whether we should make it off of the reference genome that someone uploads. I'm leading towards the latter, but the former may be nice. 

Thoughts?

**Comment by thw17** [comment]
I didn't design the program to take an official Y.  It automatically grabs it from the reference genome provided.

**Comment by mathbionerd** [comment]
I just made a set of reference BED files with the coordinates of the PARs on the Y chromosome in GRCh38/hg38 and GRCh37/hg19: 

[https://github.com/WilsonSayresLab/XYalign/tree/master/Files/PARs](https://github.com/WilsonSayresLab/XYalign/tree/master/Files/PARs)

Next step is to mask out (s/A|T|G|C|a|t|g|c/N/g) these regions on the reference Y chromosome that is extracted from the reference BAM file. I can see value in just having these as reference files, instead of having to remask this every time. Thoughts?

**Comment by thw17** [comment]
Just added capability of taking a bed file to mask the reference
