### ISSUE TITLE
Incorporate reference genome mask into XYalign

### ISSUE THREAD

**Issue by mathbionerd** [WilsonSayresLab/XYalign#6]
Incorporate reference genome mask into XYalign to improve and speed up depth and quality windowed analyses.

**Comment by thw17** [comment]
Reference map option incorporated.  No real need to speed up window analyses, as they only take a minute or two per chromosome.  They're not the bottleneck in the pipeline right now.  The real slow down is removing the sex chromosomes from the original bam and then merging the new sex chromosome bam back in.
