### ISSUE TITLE
Finalize/polish plotting functions for sexChromosomeBamTraverse.py

### ISSUE THREAD

**Issue by mathbionerd** [WilsonSayresLab/XYalign#7]
Plot output of sexChromosomeBAMTraverese 

How many options will there be? Suggestions: 
- flag to print or not print these plots (both before/after XYalign)
- flag to print or not print out the text file that can be used to make these plots

**Comment by mathbionerd** [comment]
@thw17 does XYalign.py plot depth and quality in bins before and after realignment?

**Comment by thw17** [comment]
Not yet, next on my list though and it'll be very easy to implement.
