### ISSUE TITLE
Identify differences in variant calling for X and Y before/after XYalign

### ISSUE THREAD

**Issue by mathbionerd** [WilsonSayresLab/XYalign#8]
Assess how CNV/SV and SNF/indel variant calling varies on the X and Y chromosome before/after XYalign: 
- NA12878 GIAB sample
- 24 high coverage 1000 genomes datasets (GRCh38 reference)
- Simulated datasets (XX, XY, X0, XXY - maternal, XXY - paternal, XYY)

**Comment by thw17** [comment]
Phil - I added a function to call variants with platypus.  Right now the command line for the call looks like:

"platypus callVariants --bamFiles {} -o {} --refFile {} --nCPU {} --regions {} --assemble 1".format(bam, output_file, ref, cpus, regions)

Is there anything else you'd like me to add?

**Comment by mathbionerd** [comment]
@Phillip-a-richmond do you have additional suggestions (see @thw17's comment above).

**Comment by Phillip-a-richmond** [comment]
So the --regions option is a comma-separated list of chr:start-end, and I believe it's intended for multi-processing over different chromosomes.  Instead, I believe we want to use the --skipRegionsFile, where you pass in the "bad regions" identified in the XYalign analysis.

**Comment by thw17** [comment]
The --regions list is the regions to include.  It accepts a comma-separated list of chr:start-end OR chr.  The latter of which is implemented in xyalign.py to allow users to select the chromosomes they want to analyze.  I haven't implemented anything in regards to filtering out regions yet.

**Comment by thw17** [comment]
Ahh, I see the confusion.  Right now, the "mask" included is actually a list of regions to include.  It's provided as a bed file, based on the online documentation that said it accepts text files with one region per line.  I hadn't paid too much attention, but it's calling variants in the right places.  I should investigate this further though.

**Comment by Phillip-a-richmond** [comment]
Hey Tanya I was wondering what the status was for the variant calling pre- and post- mask for the X and Y chromosomes?  Also, I know it's in a separate thread, but did you get EAGLE working with simulated variants?
